theme: jekyll-theme-slate
title: Let your listeners send value to your podcast using Satoshis.Stream
description: Satoshis.Stream enables value sending to your podcast. Listeners use a value-enabled player (like Breez or Sphinx) and using this service you can earn sats as a podcaster!
